### ISSUE TITLE
Error baking simulation: json.decoder.JSONDecodeError: Expecting value

### ISSUE THREAD

**Issue by pskl** [rlguy/Blender-FLIP-Fluids#410]
`json.decoder.JSONDecodeError: Expecting value`

#### System Information

**Blender Version (including hash):** 2.79
**FLIP Fluids Version:** 9.0.5
**Operating System:** Windows 8
**CPU:** i5 3500k
**GFX:** GTX 1070
**RAM:** 16 Go

#### Describe the bug

Any bake attempt fails with this error.

#### To Reproduce

Try to bake

#### Expected Behaviour

Bakes fluids

#### Actual Behaviour

Bake does not happen

Super weird bug and I find it hard to believe its related to Flip Fluids itself.

**Comment by rlguy** [comment]
Hi pskl,

Thanks for the report! Would you be able to attach the full error message? This will tell me more about where this error is happening. You can see the full error message in Windows by toggling the Blender System Console (**Blender > Window > Toggle System Console**). Or on MacOS/Linux, you can view the error by running Blender from the terminal/command-line.

Does this error still happen if you delete the FLIP Fluids cache directory or set it to a new empty directory ([FLIP Fluid Cache Panel](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Domain-Cache-Settings#parameters))?

\- Ryan

**Comment by pskl** [comment]
Tried deleting local files and didnt work.
 Here is the full error still there:
```
Traceback (most recent call last):
  File "C:\Users\Jean-Eudes\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\flip_fluids_addon\operators\bake_operators.py", line 272, in execute
    self._reset_bake(context)
  File "C:\Users\Jean-Eudes\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\flip_fluids_addon\operators\bake_operators.py", line 86, in _reset_bake
    dprops.stats.refresh_stats()
  File "C:\Users\Jean-Eudes\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\flip_fluids_addon\properties\domain_stats_properties.py", line 254, in refresh_stats
    self._update_cache_stats()
  File "C:\Users\Jean-Eudes\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\flip_fluids_addon\properties\domain_stats_properties.py", line 439, in _update_cache_stats
    cachedata = json.loads(f.read())
  File "C:\Program Files\Blender Foundation\Blender\2.79\python\lib\json\__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\Blender Foundation\Blender\2.79\python\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\Blender Foundation\Blender\2.79\python\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
 
location: <unknown location>:-1
```

**Comment by pskl** [comment]
Solved it by deleting the cache, weird bug.

**Comment by rlguy** [comment]
Thanks for the update!

From the error it looks like the cache became corrupted somehow. The addon writes some data into files using the JSON file format. The addon tried to read the file at later stage in the simulation, but the problem was that the file was not completely written to your drive so there was an error produced by the JSON file decoder.

Deleting the cache removed this corrupted file. I'll see if there is a way for the addon to better handle this error so that baking doesn't stop if this happens again.

\- Ryan
