### ISSUE TITLE
Error opening test files

### ISSUE THREAD

**Issue by jasoncstudios** [rlguy/Blender-FLIP-Fluids#433]
Blender 2.79b f4dc9fd68b

FLIP Fluids 1?? That's what it says in my blender user prefs but not sure where else to check this. I just downloaded today.

Windows 10 
Intel Xeon CPU E5-2667 v4 @ 3.20GHz 32 CPUs
2x GTX 1080
256gb RAM

Baking works fine when I create scene but when I try to load a test scene I get an error and baking fails.

Open test file on my machine.

I expected the scene to bake.

The scene didn't bake and I got an error message. 
``Traceback (most recent call last):
  File "C:\Users\Jason.Carmen\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\flip_fluids_addon\operators\export_operators.py", line 131, in modal
    self._export_simulation_data_file()
  File "C:\Users\Jason.Carmen\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\flip_fluids_addon\operators\export_operators.py", line 95, in _export_simulation_data_file
    dprops.bake.export_filepath
  File "C:\Users\Jason.Carmen\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\flip_fluids_addon\export.py", line 432, in export
    __export_simulation_data_to_file(context, simulation_objects, filepath)
  File "C:\Users\Jason.Carmen\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\flip_fluids_addon\export.py", line 35, in __export_simulation_data_to_file
    data = __get_simulation_data_dict(context, simobjects)
  File "C:\Users\Jason.Carmen\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\flip_fluids_addon\export.py", line 132, in __get_simulation_data_dict
    simobjects.obstacle_meshes
  File "C:\Users\Jason.Carmen\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\flip_fluids_addon\export.py", line 316, in __get_obstacle_data
    data = utils.flip_fluid_object_to_dict(obj, obj.flip_fluid.obstacle)
  File "C:\Users\Jason.Carmen\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\flip_fluids_addon\utils\export_utils.py", line 37, in flip_fluid_object_to_dict
    item = getattr(group, identifier)
AttributeError: 'FlipFluidObstacleProperties' object has no attribute 'whitewater_influence'

location: <unknown location>:-1``

**Comment by rlguy** [comment]
Hi jasoncstudios,

We will need the FLIP Fluids version to look further into this issue. If you cannot find the version, you can take a screenshot of the FLIP Fluids user preferences menu in **File > User Preferences > Addons > FLIP Fluids**. 

You can also attach your Blender system info file. This file can be found in **Blender > Help > Save System Info**.

\- Ryan

**Comment by rlguy** [comment]
I'll be closing this issue due to inactivity. If you have any more information to add, feel free to comment or send us a message at flip.fluids@gmail.com.
