### ISSUE TITLE
Unable to open old simulation with 1.0.5

### ISSUE THREAD

**Issue by gogobd** [rlguy/Blender-FLIP-Fluids#467]
#### System Information

**Blender Version (including hash): 2.79b 2018-03-22 14:10 f4dc9f9**
**FLIP Fluids Version: 1.0.5 commit 6445a1ee8ba637bc222212220886db98ff3e8dff**
**Operating System: MacOS Mojave**
**CPU: Intel Core i5**
**GFX: Intel Iris**
**RAM: 16GB**

#### Describe the bug

When I open a .blend file that contains a FLIP Fluids simulation that has been created using 1.0.2 it doesn't open (can't load meshes etc.), because the data structures have changed:

```
Read blend: …/old_flip_fluids.blend
Traceback (most recent call last):
  File "/Users/…/Library/Application Support/Blender/2.79/scripts/addons/flip_fluids_addon/__init__.py", line 113, in load_post
    properties.load_post()
  File "/Users/…/Library/Application Support/Blender/2.79/scripts/addons/flip_fluids_addon/properties/__init__.py", line 60, in load_post
    object_properties.load_post()
  File "/Users/…/Library/Application Support/Blender/2.79/scripts/addons/flip_fluids_addon/properties/object_properties.py", line 344, in load_post
    domain_properties.load_post()
  File "/Users/…/Library/Application Support/Blender/2.79/scripts/addons/flip_fluids_addon/properties/domain_properties.py", line 316, in load_post
    dprops.load_post()
  File "/Users/…/Library/Application Support/Blender/2.79/scripts/addons/flip_fluids_addon/properties/domain_properties.py", line 273, in load_post
    self.bake.load_post()
  File "/Users/…/Library/Application Support/Blender/2.79/scripts/addons/flip_fluids_addon/properties/domain_bake_properties.py", line 73, in load_post
    self.check_autosave()
  File "/Users/…/Library/Application Support/Blender/2.79/scripts/addons/flip_fluids_addon/properties/domain_bake_properties.py", line 112, in check_autosave
    self.original_frame_start = autosave_info['frame_start']
KeyError: 'frame_start'
Traceback (most recent call last):
  File "/Users/…/Library/Application Support/Blender/2.79/scripts/addons/flip_fluids_addon/__init__.py", line 82, in frame_change_pre
    render.frame_change_pre(scene)
  File "/Users/…/Library/Application Support/Blender/2.79/scripts/addons/flip_fluids_addon/render.py", line 30, in frame_change_pre
    __load_frame(__get_current_frame())
  File "/Users/…/Library/Application Support/Blender/2.79/scripts/addons/flip_fluids_addon/render.py", line 429, in __load_frame
    __load_surface_frame(frameno, force_reload)
  File "/Users/…/Library/Application Support/Blender/2.79/scripts/addons/flip_fluids_addon/render.py", line 153, in __load_surface_frame
    cache.surface.load_frame(frameno, force_load)
  File "/Users/…/Library/Application Support/Blender/2.79/scripts/addons/flip_fluids_addon/objects/flip_fluid_cache.py", line 212, in load_frame
    self._initialize_bounds_data(frameno)
  File "/Users/…/Library/Application Support/Blender/2.79/scripts/addons/flip_fluids_addon/objects/flip_fluid_cache.py", line 638, in _initialize_bounds_data
    self.bounds.set(bounds_data)
  File "/Users/…/Library/Application Support/Blender/2.79/scripts/addons/flip_fluids_addon/objects/flip_fluid_cache.py", line 63, in set
    self.isize = bounds_dict['isize']
KeyError: 'isize'
```

Unfortunately I would have to either roll back the addon or re-bake the simulation. I don't know if it was ever planned to support opening older versions, so I thought it would be adequate to report this as a bug.

#### To Reproduce

It should be sufficient to try to open any 1.0.2 simulation with 1.0.5

#### Expected Behaviour

Simulation should load

#### Actual Behaviour

It doesn't.

#### Screenshots

-

FLIP Fluids is really really awesome, it would be great to have a path to migrate old bakes.

**Comment by rlguy** [comment]
Hi gogobd,

I am sorry to say that we are unable to support loading cache directories generated by previous versions of the addon and do not have plans to support older caches in the future.

The cache system and structure was completely re-written in version 1.0.5 to support a future [decoupled baking feature](https://github.com/rlguy/Blender-FLIP-Fluids/issues/296) and to fix a serious [crashing issue during animation export](https://github.com/rlguy/Blender-FLIP-Fluids/issues/401). Because of this re-write and structure change, the addon will not be able to load caches generated by older versions of the addon.

We do not plan to add custom code to support loading older caches in the future. Loading a FLIP Fluids cache and handling playback/rendering is a large part of the addon code base. Adding custom code to support older caches would be a large undertaking which would slow down development, would risk introducing bugs into the addon, and would be difficult to maintain in future development.

\- Ryan

**Comment by gogobd** [comment]
I guess I could always just install the previous version into another instance of blender and export whatever I'd need. FLIP Fluids now has so many new features I can totally understand your development decision. Thanks for your quick response - and for your amazing work!
