### ISSUE TITLE
missing file libblpyfluid.so

### ISSUE THREAD

**Issue by discon-nected** [rlguy/Blender-FLIP-Fluids#478]
I compiled Flip Fluids from source on Ubuntu 16.04. When I try to bake a simulation I get this error...
```
Exporting Simulation Meshes:
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/realcourse/.config/blender/2.81/scripts/addons/flip_fluids_addon/bake.py", line 1713, in bake
    fluidsim = FluidSimulation(init_data.isize, init_data.jsize, init_data.ksize, init_data.dx)
  File "/home/realcourse/.config/blender/2.81/scripts/addons/flip_fluids_addon/pyfluid/fluidsimulation.py", line 65, in __init__
    self._init_from_dimensions(isize, jsize, ksize, dx)
  File "/home/realcourse/.config/blender/2.81/scripts/addons/flip_fluids_addon/pyfluid/method_decorators.py", line 68, in check_values
    return func(self, *args)
  File "/home/realcourse/.config/blender/2.81/scripts/addons/flip_fluids_addon/pyfluid/fluidsimulation.py", line 81, in _init_from_dimensions
    libfunc = lib.FluidSimulation_new_from_dimensions
  File "/home/realcourse/.config/blender/2.81/scripts/addons/flip_fluids_addon/pyfluid/pyfluid.py", line 39, in __getattr__
    self._lib = self._load_library("pyfluid")
  File "/home/realcourse/.config/blender/2.81/scripts/addons/flip_fluids_addon/pyfluid/pyfluid.py", line 57, in _load_library
    raise LibraryLoadError("Cannot find fluid engine library: " + libname)
flip_fluids_addon.pyfluid.pyfluid.LibraryLoadError: 'Cannot find fluid engine library: libblpyfluid.so'
------------------------------------------------------------
Simulation Ended.
Thank you for using FLIP Fluids!
```
Not sure where `libblpyfluid.so` should be located or where it comes from but I can confirm it is neither in the source or compiled files.
The compiled `pyfluid/lib` directory is empty

**Comment by rlguy** [comment]
Hi discon-nected,

This issue tracker is only meant for reporting bugs for the FLIP Fluids product distributed on the Blender Market. We are not able to provide support on compiling the GitHub source.

After the compilation completes successfully, the ```libblpyfluid.so``` library should be located at ```flip_fluids_addon/pyfluid/lib/libblpyfluid.so```. The end of the compile/make output should list where the file is located. Example output (on Windows, but Linux output is similar):

```
.
.
.
[ 76%] Building CXX object CMakeFiles/objects.dir/src/engine/c_bindings/cbindings.cpp.obj
[ 78%] Building CXX object CMakeFiles/objects.dir/src/engine/c_bindings/fluidsimulation_c.cpp.obj
[ 80%] Building CXX object CMakeFiles/objects.dir/src/engine/c_bindings/forcefield_c.cpp.obj
[ 82%] Building CXX object CMakeFiles/objects.dir/src/engine/c_bindings/forcefieldgrid_c.cpp.obj
[ 83%] Building CXX object CMakeFiles/objects.dir/src/engine/c_bindings/forcefieldpoint_c.cpp.obj
[ 85%] Building CXX object CMakeFiles/objects.dir/src/engine/c_bindings/forcefieldsurface_c.cpp.obj
[ 87%] Building CXX object CMakeFiles/objects.dir/src/engine/c_bindings/meshfluidsource_c.cpp.obj
[ 89%] Building CXX object CMakeFiles/objects.dir/src/engine/c_bindings/meshobject_c.cpp.obj
[ 91%] Building CXX object CMakeFiles/objects.dir/src/engine/c_bindings/openclutils_c.cpp.obj
[ 92%] Building CXX object CMakeFiles/objects.dir/src/engine/kernels/kernels.cpp.obj
[ 94%] Building CXX object CMakeFiles/objects.dir/src/engine/opencl_bindings/clcpp.cpp.obj
[ 94%] Built target objects
Scanning dependencies of target pyfluid
[ 96%] Linking CXX shared library bl_flip_fluids\pyfluid\lib\libpyfluid.dll
[ 96%] Built target pyfluid
Scanning dependencies of target bl_flip_fluids
[ 98%] Linking CXX executable bl_flip_fluids\test\engine_test.exe
[ 98%] Built target bl_flip_fluids
Scanning dependencies of target blpyfluid
[100%] Linking CXX shared library bl_flip_fluids\flip_fluids_addon\pyfluid\lib\libblpyfluid.dll
[100%] Built target blpyfluid
```

I would suggest checking for any compile errors if the library is not present. We are using Ubuntu 16.04 with the gcc/g++ 4.8 compiler for building the addon.

**Comment by discon-nected** [comment]
For what it's worth I upgraded to gcc/g++4.8 and recompiled. No error messages but also no file locations listed...
```
cmake ..
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/user/Documents/BLENDER ADDONS/FipFluids/try2/Blender-FLIP-Fluids/build
```

**Comment by rlguy** [comment]
It looks like you have not yet compiled the source. The ```cmake ..``` command is the first step to generate the project Makefiles for your system. The next step is to compile the program. See the build instructions section of the README.md: https://github.com/rlguy/Blender-FLIP-Fluids#building

If you have the GNU Make utility in your path, you can start compiling with command ```make```.

**Comment by discon-nected** [comment]
arf. thanks, not enough sleep i guess  :D
