### ISSUE TITLE
Quaternion and axis-angle keyframed rotation is not supported

### ISSUE THREAD

**Issue by rlguy** [rlguy/Blender-FLIP-Fluids#515]
It has been reported that if an object is exported with keyframe animated quaternion or axis-angle rotation, the object motion will not be matched correctly within the simulator or will generate an error. It looks like this bug has been in the addon since version 1.0.4 (Aug 2018).

In the current version 1.0.9, quaternion motion will not match correctly, and if axis-angle rotation is used, an error will be generated: 

```
Python: Traceback (most recent call last):
  File "C:\Users\ryanl\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\flip_fluids_addon\operators\export_operators.py", line 137, in modal
    is_finished = self.geometry_exporter.update_export(self.export_step_time)
  File "C:\Users\ryanl\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\flip_fluids_addon\objects\flip_fluid_geometry_exporter.py", line 134, in update_export
    raise e
  File "C:\Users\ryanl\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\flip_fluids_addon\objects\flip_fluid_geometry_exporter.py", line 124, in update_export
    self._process_work_item(work_item)
  File "C:\Users\ryanl\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\flip_fluids_addon\objects\flip_fluid_geometry_exporter.py", line 484, in _process_work_item
    self._process_mesh_object(work_item)
  File "C:\Users\ryanl\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\flip_fluids_addon\objects\flip_fluid_geometry_exporter.py", line 385, in _process_mesh_object
    matrix_world = work_item.geometry_export_object.get_matrix_world_at_frame(frame_id)
  File "C:\Users\ryanl\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\flip_fluids_addon\objects\flip_fluid_geometry_export_object.py", line 372, in get_matrix_world_at_frame
    return get_matrix_world_at_frame(bl_object, frame_id)
  File "C:\Users\ryanl\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\flip_fluids_addon\objects\flip_fluid_geometry_export_object.py", line 70, in get_matrix_world_at_frame
    axis = Vector(axis_angle[1], axis_angle[2], axis_angle[3])
TypeError: mathutils.Vector(): more than a single arg given
```

Euler rotation is still fully supported.

### Workaround

A workaround is to enable the _Export Animated Mesh_ option on the object.

**Comment by rlguy** [comment]
Fixed, thanks to help from [Artell](https://blendermarket.com/creators/artell)!

This fix will be available in the next experimental build v9.0.9.13 on January 27th.
