### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'keymap_items' B3.31 (LTS)

### ISSUE THREAD

**Issue by LawrenceTattrie** [rlguy/Blender-FLIP-Fluids#602]
At the end of a command line render the following error was shown:

> Attempting to open image: <C:\Users\X\Documents\hobbies\Blender\3_3_LTS\flip fluids\my_first_simulation_render\0100.png>
Exception in module unregister(): 'C:\\Program Files\\Blender Foundation\\Blender 3.3\\3.3\\scripts\\addons\\mesh_snap_utilities_line\\__init__.py'
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\modules\addon_utils.py", line 421, in disable
    mod.unregister()
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\mesh_snap_utilities_line\__init__.py", line 173, in unregister
    unregister_keymaps()
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\mesh_snap_utilities_line\__init__.py", line 136, in unregister_keymaps
    keymap_items = keymap.keymap_items
AttributeError: 'NoneType' object has no attribute 'keymap_items'
Blender quit

Attached is a full copy of the command line output of the single render
Also is attached is a another log showing a different error but I am not completely sure if this is a starup log or not.
[ff_render_error.log](https://github.com/rlguy/Blender-FLIP-Fluids/files/10142327/ff_render_error.log)
[ff_startup.log](https://github.com/rlguy/Blender-FLIP-Fluids/files/10142328/ff_startup.log)

Note: when a user chooses 'File->Save As' to create a new blender file the flip fluid options which match filename such as Cache Directory, and Render Output do not change the filename. To me they should but I am not completely sure this should be done in all circumstances.

**Comment by rlguy** [comment]
Hi LawrenceTattrie,

Thanks for the report! From the error message, this looks like the issue could be triggered by the "Mesh Snap Utilities" addon.

> File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\**mesh_snap_utilities_line_init_.py**", line 136

Does disabling this addon prevent the issue?

> Note: when a user chooses 'File->Save As' to create a new blender file the flip fluid options which match filename such as Cache Directory, and Render Output do not change the filename. To me they should but I am not completely sure this should be done in all circumstances.

If the cache has already been created, such as by beginning a simulation, the cache directory name will not automatically change. This is to prevent cache directory from being accidentally lost or disconnected from the simulation settings when saving the Blend file as a different name, such as for versioning. Let me know if I misunderstood this issue.

Let me know if you have any questions or find any other information on the issue.

**Comment by rlguy** [comment]
Closing this issue due to inactivity. For now, we'll assume this is caused by the "Mesh Snap Utilities" error but if this is not the case, let us know and we can re-open the issue and look into this further.
